### ISSUE TITLE
Pizza tracker for order status

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#114]
**Is your feature request related to a problem? Please describe.**
If there is a way we could track order completion (eg: someone has logged into the Ops app and handled the order) that would make things easier.

Steps should include:
- [ ] Verify numbers purchased route properly
- [ ] Check that hardware stock is on hand
- [ ] Extract configuration information from the person who placed the order
- [ ] Set up hardware for client (if any hardware is ordered)
- [ ] Send account welcome email if new client
- [ ] Submit port request (if porting numbers)
- [ ] Port request completes (if porting numbers)

**Describe the solution you'd like**
Could we tag an order to a specific user when they mark parts of the order as complete and log at what time they marked it as complete?

**Comment by uncheckederror** [comment]
@danry25 What do you mean by "Verify numbers purchased route properly"?

Does that mean that we got a success response back from the vendor that we attempted to purchase the numbers from? Or does that mean that we can place a call to that number and see it in FusionPBX?

@danry25 How do check what hardware is in stock?

@danry25 Is this "Extract configuration information" an automated process or something that will have to be handled by a human?

Are you imaging these items as a list or just a linear group of items?

**Comment by danry25** [comment]
> @danry25 What do you mean by "Verify numbers purchased route properly"?

We need to validate that the phone number actually routes to our server, as some vendors will tell us a number is ready to use, but not route it properly (requiring manual intervention on our part).

> @danry25 How do check what hardware is in stock?

Inventory status is a board in Erxes, possibly automatable but probably a pain.

> Are you imaging these items as a list or just a linear group of items?

A list of items that can be checked off would be ideal.

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/105669472-39a1ae00-5e94-11eb-96e0-1d1694e5e849.png)

https://acceleratenetworks.com/cart/order/56253120-7d0e-4fa9-af47-2d466b16b989

**Comment by danry25** [comment]
Hmm, could we add a button or checkbox for it in the Ops app? Perhaps this ties in with #24 in the future, where an order is marked complete when the card relating to the order on the kanban board in Erxes is moved out of the Pre-install column and any outstanding port request is completed?

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/105795087-1aad2580-5f41-11eb-8165-b9519f57c3a4.png)

![image](https://user-images.githubusercontent.com/11726956/105795383-9a3af480-5f41-11eb-9b0e-4d74628a1f30.png)

![image](https://user-images.githubusercontent.com/11726956/105795412-a6bf4d00-5f41-11eb-840c-40e6d4823ee7.png)

"Submitted" checks if the "DateSubmitted" field on the order has a value.
"Processed" checks if the "BackgroundWorkCompleted" field on the order is set to true.
"Completed" checks if the "Completed" field on the order is set to true.

![image](https://user-images.githubusercontent.com/11726956/105796606-0dde0100-5f44-11eb-8d83-d1e7f7924626.png)

You complete an order or trigger a re-running of the background work from the Ops app now.

![image](https://user-images.githubusercontent.com/11726956/105796646-22ba9480-5f44-11eb-9c24-d0139b06abb4.png)

**Comment by uncheckederror** [comment]
![image](https://user-images.githubusercontent.com/11726956/105925611-57d2ef80-5ff5-11eb-8550-e7f4febc266e.png)

![image](https://user-images.githubusercontent.com/11726956/105925647-5e616700-5ff5-11eb-9c31-73f000034432.png)

Updated the orders page to show the porting status, foc date, and completed status of each ported number in the order.

**Comment by uncheckederror** [comment]
@danry25 says we done. 🥳
